name: Check semantic conventions

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Weaver
        uses: open-telemetry/weaver/.github/actions/setup-weaver@38befce4bc68fe320d20f189465c93835ac20c12 # v0.26.1
        with:
          version: "0.26.1"

      - name: Check registry
        run: make check

      - name: Regenerate documentation
        run: make generate

      - name: Check generated documentation
        run: test -z "$(git status --short --untracked-files=all -- docs/)"
